#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged for automated code quality checks
npx lint-staged

# Additional TypeScript type checking
npx tsc --noEmit --project ./tsconfig.json
