CREATE INDEX IF NOT EXISTS idx_crop_activities_crop_id ON crop_activities(crop_id);
CREATE INDEX IF NOT EXISTS idx_crop_activities_activity_type ON crop_activities(activity_type);
CREATE INDEX IF NOT EXISTS idx_crop_activities_activity_date ON crop_activities(activity_date);
CREATE INDEX IF NOT EXISTS idx_crop_activities_composite ON crop_activities(crop_id, activity_date);
CREATE INDEX IF NOT EXISTS idx_animal_health_records_animal_id ON animal_health_records(animal_id);
CREATE INDEX IF NOT EXISTS idx_animal_health_records_check_date ON animal_health_records(check_date);
CREATE INDEX IF NOT EXISTS idx_animal_health_records_health_status ON animal_health_records(health_status);
CREATE INDEX IF NOT EXISTS idx_animal_health_records_composite ON animal_health_records(animal_id, check_date);
CREATE INDEX IF NOT EXISTS idx_animal_production_animal_id ON animal_production(animal_id);
CREATE INDEX IF NOT EXISTS idx_animal_production_production_type ON animal_production(production_type);
CREATE INDEX IF NOT EXISTS idx_animal_production_production_date ON animal_production(production_date);
CREATE INDEX IF NOT EXISTS idx_animal_production_composite ON animal_production(animal_id, production_date);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_inventory_id ON inventory_transactions(inventory_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_transaction_type ON inventory_transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_created_at ON inventory_transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_composite ON inventory_transactions(inventory_id, created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_inventory_id ON inventory_alerts(inventory_id);
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_alert_type ON inventory_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_severity ON inventory_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_resolved ON inventory_alerts(resolved);
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_alert_date ON inventory_alerts(alert_date);
CREATE INDEX IF NOT EXISTS idx_finance_entries_category ON finance_entries(category);
CREATE INDEX IF NOT EXISTS idx_finance_entries_subcategory ON finance_entries(subcategory);
CREATE INDEX IF NOT EXISTS idx_finance_entries_vendor_customer ON finance_entries(vendor_customer);
CREATE INDEX IF NOT EXISTS idx_finance_entries_tags ON finance_entries(tags);
CREATE INDEX IF NOT EXISTS idx_equipment_farm_id ON equipment(farm_id);
CREATE INDEX IF NOT EXISTS idx_equipment_type ON equipment(type);
CREATE INDEX IF NOT EXISTS idx_equipment_status ON equipment(status);
CREATE INDEX IF NOT EXISTS idx_equipment_last_maintenance_date ON equipment(last_maintenance_date);
CREATE INDEX IF NOT EXISTS idx_equipment_next_maintenance_date ON equipment(next_maintenance_date);
CREATE INDEX IF NOT EXISTS idx_weather_data_farm_id ON weather_data(farm_id);
CREATE INDEX IF NOT EXISTS idx_weather_data_date ON weather_data(date);
CREATE INDEX IF NOT EXISTS idx_weather_data_temperature_high ON weather_data(temperature_high);
CREATE INDEX IF NOT EXISTS idx_weather_data_temperature_low ON weather_data(temperature_low);
CREATE INDEX IF NOT EXISTS idx_weather_data_precipitation ON weather_data(precipitation);
CREATE INDEX IF NOT EXISTS idx_notifications_farm_id ON notifications(farm_id);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_composite ON notifications(user_id, read, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_farm_id ON audit_logs(farm_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_record_id ON audit_logs(record_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_composite ON audit_logs(table_name, created_at);
CREATE INDEX IF NOT EXISTS idx_session_tracking_is_active ON session_tracking(is_active);
CREATE INDEX IF NOT EXISTS idx_session_tracking_logout_time ON session_tracking(logout_time);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_email ON password_reset_tokens(email);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_used ON password_reset_tokens(used);
CREATE INDEX IF NOT EXISTS idx_token_revocation_user_id ON token_revocation(user_id);
CREATE INDEX IF NOT EXISTS idx_token_revocation_revoked_at ON token_revocation(revoked_at);
CREATE INDEX IF NOT EXISTS idx_crop_rotation_plans_farm_id ON crop_rotation_plans(farm_id);
CREATE INDEX IF NOT EXISTS idx_crop_rotation_plans_field_id ON crop_rotation_plans(field_id);
CREATE INDEX IF NOT EXISTS idx_crop_rotation_plans_status ON crop_rotation_plans(status);
CREATE INDEX IF NOT EXISTS idx_crop_rotation_plans_start_date ON crop_rotation_plans(start_date);
CREATE INDEX IF NOT EXISTS idx_crop_rotation_plans_end_date ON crop_rotation_plans(end_date);
CREATE INDEX IF NOT EXISTS idx_rotation_sequence_rotation_plan_id ON rotation_sequence(rotation_plan_id);
CREATE INDEX IF NOT EXISTS idx_rotation_sequence_sequence_order ON rotation_sequence(sequence_order);
CREATE INDEX IF NOT EXISTS idx_rotation_sequence_crop_type ON rotation_sequence(crop_type);
CREATE INDEX IF NOT EXISTS idx_rotation_sequence_planting_date ON rotation_sequence(planting_date);
CREATE INDEX IF NOT EXISTS idx_pest_diseases_type ON pest_diseases(type);
CREATE INDEX IF NOT EXISTS idx_pest_diseases_severity_level ON pest_diseases(severity_level);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_farm_id ON crop_pest_disease_records(farm_id);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_crop_id ON crop_pest_disease_records(crop_id);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_pest_disease_id ON crop_pest_disease_records(pest_disease_id);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_detection_date ON crop_pest_disease_records(detection_date);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_severity ON crop_pest_disease_records(severity);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_status ON crop_pest_disease_records(status);
CREATE INDEX IF NOT EXISTS idx_crop_pest_disease_records_composite ON crop_pest_disease_records(farm_id, status, detection_date);
CREATE INDEX IF NOT EXISTS idx_crops_farm_status_type_date ON crops(farm_id, status, crop_type, planting_date);
CREATE INDEX IF NOT EXISTS idx_crops_farm_field_status ON crops(farm_id, field_id, status);
CREATE INDEX IF NOT EXISTS idx_crops_health_status ON crops(health_status);
CREATE INDEX IF NOT EXISTS idx_crops_actual_harvest_date ON crops(actual_harvest_date);
CREATE INDEX IF NOT EXISTS idx_crops_expected_harvest_date ON crops(expected_harvest_date);
CREATE INDEX IF NOT EXISTS idx_animals_farm_species_status_date ON animals(farm_id, species, status, date_of_birth);
CREATE INDEX IF NOT EXISTS idx_animals_health_status_date ON animals(health_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_animals_purchase_date ON animals(purchase_date);
CREATE INDEX IF NOT EXISTS idx_animals_current_location_id ON animals(current_location_id);
CREATE INDEX IF NOT EXISTS idx_tasks_farm_status_priority_date ON tasks(farm_id, status, priority, due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_related_entity ON tasks(related_entity_type, related_entity_id);
CREATE INDEX IF NOT EXISTS idx_tasks_start_date ON tasks(start_date);
CREATE INDEX IF NOT EXISTS idx_tasks_completion_date ON tasks(completion_date);
CREATE INDEX IF NOT EXISTS idx_inventory_farm_category_status ON inventory(farm_id, category, status);
CREATE INDEX IF NOT EXISTS idx_inventory_expiry_date ON inventory(expiry_date);
CREATE INDEX IF NOT EXISTS idx_inventory_purchase_date ON inventory(purchase_date);
CREATE INDEX IF NOT EXISTS idx_inventory_reorder_level ON inventory(reorder_level);
CREATE INDEX IF NOT EXISTS idx_finance_entries_farm_type_category_date ON finance_entries(farm_id, entry_type, category, date);
CREATE INDEX IF NOT EXISTS idx_finance_entries_payment_method ON finance_entries(payment_method);
CREATE INDEX IF NOT EXISTS idx_finance_entries_reference_number ON finance_entries(reference_number);