// Material UI Components Export
export { default as ModernHeader } from './Header';
export { FarmThemeProvider, farmTheme, darkFarmTheme } from './theme.tsx';

// Re-export commonly used MUI components for convenience
export {
  Box,
  Container,
  Grid,
  Stack,
  Card,
  CardContent,
  CardActions,
  CardHeader,
  Typography,
  Button,
  IconButton,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Chip,
  Avatar,
  Badge,
  Divider,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Menu,
  MenuItem as MenuItemComponent,
  AppBar,
  Toolbar,
  Drawer,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Pagination,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Alert,
  AlertTitle,
  Snackbar,
  CircularProgress,
  LinearProgress,
  Tabs,
  Tab,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Switch,
  Checkbox,
  Radio,
  RadioGroup,
  FormControlLabel,
  FormGroup,
  Tooltip,
  Popover,
  Skeleton,
  Fab,
} from '@mui/material';

// Icons
export {
  Search,
  Notifications,
  Settings,
  Logout,
  AccountCircle,
  Agriculture,
  LocationOn,
  Add,
  BarChart,
  ExpandMore,
  Close,
  Edit,
  Delete,
  Save,
  Cancel,
  Check,
  Warning,
  Error,
  Info,
  CheckCircle as Success,
  TrendingUp,
  TrendingDown,
  CalendarToday,
  Schedule,
  Assignment,
  Dashboard,
  People,
  Inventory,
  ShoppingCart,
  LocalShipping,
  Assessment,
  Analytics,
  Cloud,
  Opacity,
  Thermostat,
  WbSunny,
  Grass,
  Spa,
  LocalFlorist,
  Yard,
  Forest,
  Terrain,
  Map,
  GpsFixed,
  MyLocation,
  Directions,
  NavigateNext,
  NavigateBefore,
  FirstPage,
  LastPage,
  Refresh,
  FilterList,
  Sort,
  ViewList,
  ViewModule,
  ViewColumn,
  MoreVert,
  MoreHoriz,
  DragIndicator,
  DragHandle,
  OpenInNew,
  Download,
  Upload,
  Print,
  Share,
  Favorite,
  Bookmark,
  Star,
  ThumbUp,
  ThumbDown,
  Comment,
  Send,
  AttachFile,
  Image,
  VideoLibrary,
  AudioFile,
  Description,
  Folder,
  FolderOpen,
  CloudUpload,
  CloudDownload,
  Sync,
  Backup,
  Restore,
  Security,
  Lock,
  LockOpen,
  Visibility,
  VisibilityOff,
  EditNote,
  NoteAdd,
  DeleteSweep,
  CleaningServices,
  Build,
  Handyman,
  Construction,
  Engineering,
  Science,
  Biotech,
  HealthAndSafety,
  MedicalServices,
  LocalHospital as Hospital,
  LocalPharmacy,
  Coronavirus,
  Masks as Mask,
  Sanitizer,
  WaterDrop,
  Air,
  Co2,
  EnergySavingsLeaf,
  Recycling,
  DeleteForever,
  DeleteOutline,
  RestoreFromTrash,
  Archive,
  Unarchive,
  Inbox,
  Outbox,
  SendAndArchive,
  MarkEmailRead,
  MarkEmailUnread,
  Email,
  Phone,
  Sms,
  WhatsApp,
  Facebook,
  Twitter,
  Instagram,
  LinkedIn,
  YouTube,
  Language,
  Public,
  Public as Globe,
  Satellite,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothConnected,
  BluetoothDisabled,
  Usb,
  Power,
  PowerOff,
  PowerSettingsNew,
  BatteryFull,
  BatteryChargingFull,
  BatteryAlert,
  Battery0Bar,
  Battery1Bar,
  Battery2Bar,
  Battery3Bar,
  Battery4Bar,
  Battery5Bar,
  Battery6Bar,
  SignalCellularAlt,
  SignalCellularAlt1Bar,
  SignalCellularAlt2Bar,
  SignalWifi4Bar,
  SignalWifiOff,
  NetworkCheck,
  NetworkLocked,
  NetworkPing,
  Router,
  Storage,
  SdStorage,
  SimCard,
  Memory,
  Memory as MemoryIcon,
  Storage as HardDrive,
  SdCard as Ssd,
  Hardware as Hdd,
  CloudQueue,
  CloudDone,
  CloudCircle,
  CloudSync,
  CloudOff,
  CloudDownload as CloudDownloadIcon,
  CloudUpload as CloudUploadIcon,
  CloudQueue as CloudQueueIcon,
  CloudDone as CloudDoneIcon,
  CloudCircle as CloudCircleIcon,
  CloudSync as CloudSyncIcon,
  CloudOff as CloudOffIcon,
  Cloud as CloudIcon,
  Foggy,
  FilterDrama as Haze,
  FilterDrama as Mist,
  Snowing,
  AcUnit,
  BeachAccess,
  HotTub,
  Pool,
  Water,
  WaterDamage,
  Waves,
  Tsunami,
  Flood,
  Storm,
  Thunderstorm,
  Bolt as Lightning,
  FlashlightOn as Flashlight,
  FlashlightOn,
  FlashlightOff,
  Lightbulb,
  LightbulbOutline,
  LightMode,
  DarkMode,
  Contrast,
  BrightnessHigh,
  BrightnessLow,
  BrightnessMedium,
  Brightness4,
  Brightness5,
  Brightness6,
  Brightness7,
  WbAuto,
  WbIncandescent,
  WbIridescent,
  WbShade,
  WbSunny as WbSunnyIcon,
  WbTwilight,
  WbCloudy,
  WbTwilight as WbTwilightIcon,
  WbCloudy as WbCloudyIcon,
  NightsStay,
  Bedtime,
  Nightlight,
  NightlightRound,
  Bedtime as BedtimeIcon,
  NightsStay as NightsStayIcon,
  Nightlight as NightlightIcon,
  NightlightRound as NightlightRoundIcon,
  Hotel,
  SingleBed,
  KingBed,
  Weekend,
  Event,
  EventAvailable,
  EventBusy,
  EventNote,
  CalendarMonth,
  DateRange,
  Today,
  Update,
  AccessTime,
  AccessTimeFilled,
  Schedule as ScheduleIcon,
  ScheduleSend,
  PendingActions,
  Timelapse,
  Timer,
  Timer10,
  Timer3,
  TimerOff,
  HourglassEmpty,
  HourglassFull,
  HourglassBottom,
  HourglassTop,
  HourglassDisabled,
  Timer as Stopwatch,
  Timer3Select as TimerSelect,
} from '@mui/icons-material';
