// Material UI Components Export
export { default as ModernHeader } from './Header';
export { FarmThemeProvider, farmTheme, darkFarmTheme } from './theme.tsx';

// Re-export commonly used MUI components for convenience
export {
  Box,
  Container,
  Grid,
  Stack,
  Card,
  CardContent,
  CardActions,
  CardHeader,
  Typography,
  Button,
  IconButton,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Chip,
  Avatar,
  Badge,
  Divider,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Menu,
  MenuItem as MenuItemComponent,
  AppBar,
  Toolbar,
  Drawer,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Pagination,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Alert,
  AlertTitle,
  Snackbar,
  CircularProgress,
  LinearProgress,
  Tabs,
  Tab,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Switch,
  Checkbox,
  Radio,
  RadioGroup,
  FormControlLabel,
  FormGroup,
  Tooltip,
  Popover,
  Skeleton,
  Fab,
} from '@mui/material';

// Icons
export {
  Search,
  Notifications,
  Settings,
  Logout,
  AccountCircle,
  Agriculture,
  LocationOn,
  Add,
  BarChart,
  ExpandMore,
  Close,
  Edit,
  Delete,
  Save,
  Cancel,
  Check,
  Warning,
  Error,
  Info,
  Success,
  TrendingUp,
  TrendingDown,
  CalendarToday,
  Schedule,
  Assignment,
  Dashboard,
  People,
  Inventory,
  ShoppingCart,
  LocalShipping,
  Assessment,
  Analytics,
  Cloud,
  Opacity,
  Thermostat,
  WbSunny,
  Grass,
  Spa,
  Eco,
  Compost,
  LocalFlorist,
  Yard,
  Forest,
  Terrain,
  Map,
  GpsFixed,
  MyLocation,
  Directions,
  NavigateNext,
  NavigateBefore,
  FirstPage,
  LastPage,
  Refresh,
  FilterList,
  Sort,
  ViewList,
  ViewModule,
  ViewColumn,
  MoreVert,
  MoreHoriz,
  DragIndicator,
  DragHandle,
  OpenInNew,
  Download,
  Upload,
  Print,
  Share,
  Favorite,
  Bookmark,
  Star,
  ThumbUp,
  ThumbDown,
  Comment,
  Send,
  AttachFile,
  Image,
  VideoLibrary,
  AudioFile,
  Description,
  Folder,
  FolderOpen,
  CloudUpload,
  CloudDownload,
  Sync,
  Backup,
  Restore,
  Security,
  Lock,
  LockOpen,
  Visibility,
  VisibilityOff,
  EditNote,
  NoteAdd,
  DeleteSweep,
  CleaningServices,
  Build,
  Handyman,
  Construction,
  Engineering,
  Science,
  Biotech,
  HealthAndSafety,
  MedicalServices,
  Hospital,
  LocalPharmacy,
  Coronavirus,
  Mask,
  Sanitizer,
  WaterDrop,
  Air,
  Co2,
  EnergySavingsLeaf,
  Recycling,
  Compost as CompostIcon,
  DeleteForever,
  DeleteOutline,
  RestoreFromTrash,
  Archive,
  Unarchive,
  Inbox,
  Outbox,
  SendAndArchive,
  MarkEmailRead,
  MarkEmailUnread,
  Email,
  Phone,
  Sms,
  WhatsApp,
  Facebook,
  Twitter,
  Instagram,
  LinkedIn,
  YouTube,
  Language,
  Public,
  Globe,
  Satellite,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothConnected,
  BluetoothDisabled,
  Usb,
  Power,
  PowerOff,
  PowerSettingsNew,
  BatteryFull,
  BatteryChargingFull,
  BatteryAlert,
  Battery0Bar,
  Battery1Bar,
  Battery2Bar,
  Battery3Bar,
  Battery4Bar,
  Battery5Bar,
  Battery6Bar,
  SignalCellularAlt,
  SignalCellularAlt1Bar,
  SignalCellularAlt2Bar,
  SignalWifi4Bar,
  SignalWifiOff,
  NetworkCheck,
  NetworkLocked,
  NetworkPing,
  Router,
  Storage,
  SdStorage,
  SimCard,
  Memory,
  Memory as MemoryIcon,
  HardDrive,
  Ssd,
  Hdd,
  CloudQueue,
  CloudDone,
  CloudCircle,
  CloudSync,
  CloudOff,
  CloudDownload as CloudDownloadIcon,
  CloudUpload as CloudUploadIcon,
  CloudQueue as CloudQueueIcon,
  CloudDone as CloudDoneIcon,
  CloudCircle as CloudCircleIcon,
  CloudSync as CloudSyncIcon,
  CloudOff as CloudOffIcon,
  Cloud as CloudIcon,
  Foggy,
  Haze,
  Mist,
  Snowing,
  AcUnit,
  BeachAccess,
  HotTub,
  Pool,
  Water,
  WaterDamage,
  Waves,
  Tsunami,
  Flood,
  Storm,
  Thunderstorm,
  Lightning,
  Flashlight,
  FlashlightOn,
  FlashlightOff,
  Lightbulb,
  LightbulbOutline,
  LightMode,
  DarkMode,
  Contrast,
  BrightnessHigh,
  BrightnessLow,
  BrightnessMedium,
  Brightness4,
  Brightness5,
  Brightness6,
  Brightness7,
  WbAuto,
  WbIncandescent,
  WbIridescent,
  WbShade,
  WbSunny as WbSunnyIcon,
  WbTwilight,
  WbCloudy,
  WbTwilight as WbTwilightIcon,
  WbCloudy as WbCloudyIcon,
  NightsStay,
  Bedtime,
  Nightlight,
  NightlightRound,
  Bedtime as BedtimeIcon,
  NightsStay as NightsStayIcon,
  Nightlight as NightlightIcon,
  NightlightRound as NightlightRoundIcon,
  Hotel,
  SingleBed,
  KingBed,
  Weekend,
  Event,
  EventAvailable,
  EventBusy,
  EventNote,
  CalendarMonth,
  DateRange,
  Today,
  Update,
  AccessTime,
  AccessTimeFilled,
  Schedule as ScheduleIcon,
  ScheduleSend,
  PendingActions,
  Timelapse,
  Timer,
  Timer10,
  Timer3,
  TimerOff,
  HourglassEmpty,
  HourglassFull,
  HourglassBottom,
  HourglassTop,
  HourglassDisabled,
  Stopwatch,
  TimerSelect,
  TimerSelect as TimerSelectIcon,
  TimerSelect as TimerSelectIconDuplicate,
  TimerSelect as TimerSelectIconTriplicate,
  TimerSelect as TimerSelectIconQuadruplicate,
  TimerSelect as TimerSelectIconQuintuplicate,
  TimerSelect as TimerSelectIconSextuplicate,
  TimerSelect as TimerSelectIconSeptuplicate,
  TimerSelect as TimerSelectIconOctuplicate,
  TimerSelect as TimerSelectIconNonuplicate,
  TimerSelect as TimerSelectIconDecuplicate,
  TimerSelect as TimerSelectIconUndecuplicate,
  TimerSelect as TimerSelectIconDuodecuplicate,
  TimerSelect as TimerSelectIconTredecuplicate,
  TimerSelect as TimerSelectIconQuattuordecuplicate,
  TimerSelect as TimerSelectIconQuindecuplicate,
  TimerSelect as TimerSelectIconSexdecuplicate,
  TimerSelect as TimerSelectIconSeptendecuplicate,
  TimerSelect as TimerSelectIconOctodecuplicate,
  TimerSelect as TimerSelectIconNovemdecuplicate,
  TimerSelect as TimerSelectIconVigintuplicate,
  TimerSelect as TimerSelectIconUnvigintuplicate,
  TimerSelect as TimerSelectIconDuovigintuplicate,
  TimerSelect as TimerSelectIconTrevigintuplicate,
  TimerSelect as TimerSelectIconQuattuorvigintuplicate,
  TimerSelect as TimerSelectIconQuinvigintuplicate,
  TimerSelect as TimerSelectIconSexvigintuplicate,
  TimerSelect as TimerSelectIconSeptenvigintuplicate,
  TimerSelect as TimerSelectIconOctovigintuplicate,
  TimerSelect as TimerSelectIconNovemvigintuplicate,
  TimerSelect as TimerSelectIconTrigintuplicate,
  TimerSelect as TimerSelectIconUntrigintuplicate,
  TimerSelect as TimerSelectIconDuotrigintuplicate,
  TimerSelect as TimerSelectIconTritrigintuplicate,
  TimerSelect as TimerSelectIconQuattuortrigintuplicate,
  TimerSelect as TimerSelectIconQuintrigintuplicate,
  TimerSelect as TimerSelectIconSextrigintuplicate,
  TimerSelect as TimerSelectIconSeptentrigintuplicate,
  TimerSelect as TimerSelectIconOctotrigintuplicate,
  TimerSelect as TimerSelectIconNovemtrigintuplicate,
  TimerSelect as TimerSelectIconQuadragintuplicate,
  TimerSelect as TimerSelectIconUnquadragintuplicate,
  TimerSelect as TimerSelectIconDuoquadragintuplicate,
  TimerSelect as TimerSelectIconTriaquadragintuplicate,
  TimerSelect as TimerSelectIconQuattuorquadragintuplicate,
  TimerSelect as TimerSelectIconQuinquadragintuplicate,
  TimerSelect as TimerSelectIconSexquadragintuplicate,
  TimerSelect as TimerSelectIconSeptenquadragintuplicate,
  TimerSelect as TimerSelectIconOctoquadragintuplicate,
  TimerSelect as TimerSelectIconNovemquadragintuplicate,
  TimerSelect as TimerSelectIconQuinquagintuplicate,
  TimerSelect as TimerSelectIconUnquinquagintuplicate,
  TimerSelect as TimerSelectIconDuoquinquagintuplicate,
  TimerSelect as TimerSelectIconTriaquinquagintuplicate,
  TimerSelect as TimerSelectIconQuattuorquinquagintuplicate,
  TimerSelect as TimerSelectIconQuinquinquagintuplicate,
  TimerSelect as TimerSelectIconSexquinquagintuplicate,
  TimerSelect as TimerSelectIconSeptenquinquagintuplicate,
  TimerSelect as TimerSelectIconOctoquinquagintuplicate,
  TimerSelect as TimerSelectIconNovemquinquagintuplicate,
  TimerSelect as TimerSelectIconSexagintuplicate,
  TimerSelect as TimerSelectIconUnsexagintuplicate,
  TimerSelect as TimerSelectIconDuosexagintuplicate,
  TimerSelect as TimerSelectIconTriasexagintuplicate,
  TimerSelect as TimerSelectIconQuattuorsexagintuplicate,
  TimerSelect as TimerSelectIconQuinsexagintuplicate,
  TimerSelect as TimerSelectIconSexsexagintuplicate,
  TimerSelect as TimerSelectIconSeptensexagintuplicate,
  TimerSelect as TimerSelectIconOctosexagintuplicate,
  TimerSelect as TimerSelectIconNovemsexagintuplicate,
  TimerSelect as TimerSelectIconSeptuagintuplicate,
  TimerSelect as TimerSelectIconUnseptuagintuplicate,
  TimerSelect as TimerSelectIconDuoseptuagintuplicate,
  TimerSelect as TimerSelectIconTriaeptuagintuplicate,
  TimerSelect as TimerSelectIconQuattuorseptuagintuplicate,
  TimerSelect as TimerSelectIconQuinseptuagintuplicate,
  TimerSelect as TimerSelectIconSexseptuagintuplicate,
  TimerSelect as TimerSelectIconSeptenseptuagintuplicate,
  TimerSelect as TimerSelectIconOctoseptuagintuplicate,
  TimerSelect as TimerSelectIconNovemseptuagintuplicate,
  TimerSelect as TimerSelectIconOctogintuplicate,
  TimerSelect as TimerSelectIconUnoctogintuplicate,
  TimerSelect as TimerSelectIconDuooctogintuplicate,
  TimerSelect as TimerSelectIconTriaoctogintuplicate,
  TimerSelect as TimerSelectIconQuattuoroctogintuplicate,
  TimerSelect as TimerSelectIconQuinoctogintuplicate,
  TimerSelect as TimerSelectIconSexoctogintuplicate,
  TimerSelect as TimerSelectIconSeptenoctogintuplicate,
  TimerSelect as TimerSelectIconOctooctogintuplicate,
  TimerSelect as TimerSelectIconNovemoctogintuplicate,
  TimerSelect as TimerSelectIconNonagintuplicate,
  TimerSelect as TimerSelectIconUnnonagintuplicate,
  TimerSelect as TimerSelectIconDuononagintuplicate,
  TimerSelect as TimerSelectIconTrianonagintuplicate,
  TimerSelect as TimerSelectIconQuattuornonagintuplicate,
  TimerSelect as TimerSelectIconQuinnonagintuplicate,
  TimerSelect as TimerSelectIconSexnonagintuplicate,
  TimerSelect as TimerSelectIconSeptennonagintuplicate,
  TimerSelect as TimerSelectIconOctononagintuplicate,
  TimerSelect as TimerSelectIconNovemnonagintuplicate,
  TimerSelect as TimerSelectIconCentuplicate,
  TimerSelect as TimerSelectIconUncentuplicate,
  TimerSelect as TimerSelectIconDuocentuplicate,
  TimerSelect as TimerSelectIconTriaentuplicate,
  TimerSelect as TimerSelectIconQuattuorentuplicate,
  TimerSelect as TimerSelectIconQuincentuplicate,
  TimerSelect as TimerSelectIconSexcentuplicate,
  TimerSelect as TimerSelectIconSeptencentuplicate,
  TimerSelect as TimerSelectIconOctocentuplicate,
  TimerSelect as TimerSelectIconNovemcentuplicate,
  TimerSelect as TimerSelectIconDecicentuplicate,
  TimerSelect as TimerSelectIconUndecicentuplicate,
  TimerSelect as TimerSelectIconDuodecicentuplicate,
  TimerSelect as TimerSelectIconTrescentuplicate,
  TimerSelect as TimerSelectIconQuattuorcentuplicate,
  TimerSelect as TimerSelectIconQuincentuplicate,
  TimerSelect as TimerSelectIconSexcentuplicate,
  TimerSelect as TimerSelectIconSeptencentuplicate,
  TimerSelect as TimerSelectIconOctocentuplicate,
  TimerSelect as TimerSelectIconNovemcentuplicate,
  TimerSelect as TimerSelectIconViginticentuplicate,
  TimerSelect as TimerSelectIconTrigintacentuplicate,
  TimerSelect as TimerSelectIconQuadragintacentuplicate,
  TimerSelect as TimerSelectIconQuinquagintacentuplicate,
  TimerSelect as TimerSelectIconSexagintacentuplicate,
  TimerSelect as TimerSelectIconSeptuagintacentuplicate,
  TimerSelect as TimerSelectIconOctogintacentuplicate,
  TimerSelect as TimerSelectIconNonagintacentuplicate,
  TimerSelect as TimerSelectIconCenticentuplicate,
  TimerSelect as TimerSelectIconDucenticentuplicate,
  TimerSelect as TimerSelectIconTrecenticentuplicate,
  TimerSelect as TimerSelectIconQuadringentuplicate,
  TimerSelect as TimerSelectIconQuingentuplicate,
  TimerSelect as TimerSelectIconSexcenticentuplicate,
  TimerSelect as TimerSelectIconSeptingentuplicate,
  TimerSelect as TimerSelectIconOctingentuplicate,
  TimerSelect as TimerSelectIconNongentuplicate,
  TimerSelect as TimerSelectIconMillecentuplicate,
} from '@mui/icons-material';
